services:
  app:
    build:
      context: ./app
    depends_on:
      - mongo-db
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  mongo-db:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - database:/data/db

volumes:
  database:
